version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql_pet_api
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: pets
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - pet_api_network

    laravel:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_pet_api
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        ports:
            - "8000:8000"
        environment:
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: pets
            DB_USERNAME: root
            DB_PASSWORD: secret
        depends_on:
            - mysql
        networks:
            - pet_api_network
        command: /bin/sh -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

volumes:
    mysql_data:

networks:
    pet_api_network:
        driver: bridge
